### ISSUE TITLE
提高篇第三章问题

### ISSUE THREAD

**Issue by JamesLiAndroid** [subaochen/java-tutorial#19]
这一章问题不多，我只提issue了。

![3 3](https://cloud.githubusercontent.com/assets/6966410/24085811/85164b7c-0d3d-11e7-8e7e-ca8d3543dff5.png)

![3 3](https://cloud.githubusercontent.com/assets/6966410/24085810/8514e368-0d3d-11e7-8863-5ef7ab8f1f90.png)

**Comment by subaochen** [comment]
ok。
前面两个PR怎么办？再整理一下，争取通过-)

**Comment by JamesLiAndroid** [comment]
主要是我这边以前提交的内容怎么进行合并，会不会合并之后影响主干？

**Comment by subaochen** [comment]
你在在不同的分支上提交的PR吧？这样就没有什么影响的。但是，要清理干净哪些不必要的文件，不然我合并进来，一堆无用的文件就进来了。

**Comment by subaochen** [comment]
也就是说，你在提交PR的分支上进行清理工作，清理完成我就可以合并进来了。
