### ISSUE TITLE
提高篇第四章问题

### ISSUE THREAD

**Issue by JamesLiAndroid** [subaochen/java-tutorial#20]
![1 1 1](https://cloud.githubusercontent.com/assets/6966410/24126061/e016e58a-0e06-11e7-9271-2004fb9b1b4a.png)

![1 3](https://cloud.githubusercontent.com/assets/6966410/24126060/dffdad72-0e06-11e7-81ec-915be376024a.png)

![default](https://cloud.githubusercontent.com/assets/6966410/24126059/dfd06830-0e06-11e7-844f-778994edf6af.png)

有一个问题，就是代码清单1.8和1.10放反了！

**Comment by subaochen** [comment]
补充和调整了本章的示例代码，修复了代码引用错位问题
