### ISSUE TITLE
章节7.5.1 ·「什么是Path?」, 脚注12 ：倒数第二个"反斜杠" 错误

### ISSUE THREAD

**Issue by timo1160139211** [subaochen/java-tutorial#27]
章节7.5.1 _什么是Path?_  , 脚注12 ：倒数第二个“反斜杠” 应为->“斜杠”

此处：
"在Dos操作系统中反斜杠（/）已经作为命令行参数的分隔符了"

**Comment by subaochen** [comment]
Thanks!
