### ISSUE TITLE
用户自定义异常的例子

### ISSUE THREAD

**Issue by subaochen** [subaochen/java-tutorial#5]
感觉电子商务的例子不太容易处理，可能涉及到的环节比较多，需要想一个简洁易懂的例子

**Comment by JamesLiAndroid** [comment]
应该是举一个业务逻辑方面的例子！在业务逻辑的操作中，没有系统规定的异常，这样的情况下需要自定义！

**Comment by subaochen** [comment]
已经解决，举了库存不足和价格变动无法完成交易两种情况的异常例子。
