### ISSUE TITLE
第七章的一些问题

### ISSUE THREAD

**Issue by JamesLiAndroid** [subaochen/java-tutorial#6]
由于时间比较紧，我先放图了！

![7 3](https://cloud.githubusercontent.com/assets/6966410/23532705/d0f0cab2-ffe7-11e6-9e3d-25caf5ddb401.png)

![7 4](https://cloud.githubusercontent.com/assets/6966410/23532707/d4c83ff8-ffe7-11e6-82ca-922d5fa7b316.png)

![7 6 1](https://cloud.githubusercontent.com/assets/6966410/23532708/d7db9942-ffe7-11e6-98f2-95ebef0efb6a.png)

![7 6 9 3](https://cloud.githubusercontent.com/assets/6966410/23532712/dd52c6b6-ffe7-11e6-875a-0d2a99c1243c.png)

![7 2](https://cloud.githubusercontent.com/assets/6966410/23532718/e08ea0c0-ffe7-11e6-92d0-a8dd41fbb101.png)

![7 2 1](https://cloud.githubusercontent.com/assets/6966410/23532720/e7915994-ffe7-11e6-800a-52406e03da63.png)

![7 9](https://cloud.githubusercontent.com/assets/6966410/23532723/ef0db352-ffe7-11e6-9664-f0200e598cd6.png)

![7 1](https://cloud.githubusercontent.com/assets/6966410/23532728/f8b78086-ffe7-11e6-804f-685169676e5a.png)

![7 16](https://cloud.githubusercontent.com/assets/6966410/23532737/05d87a5e-ffe8-11e6-8094-eb93b0c4a742.png)

**Comment by subaochen** [comment]
除了“迷之括号”，其他都修改了：括号之谜，我也想不起来了，只好删除了事:-(。可见，及时使用备注记下当初的想法多么重要！

**Comment by subaochen** [comment]
这一章内容感觉太多，你觉得是不是乱就一个字？有啥好建议？

**Comment by subaochen** [comment]
能直接改的问题，可以直接提交PR

**Comment by JamesLiAndroid** [comment]
我觉着第七章的内容分一下上下册吧，把带“*”号的放到提高篇

**Comment by JamesLiAndroid** [comment]
还有就是issue我继续提交，然后我fork了您的项目，我顺手把内容更正 ，您来审核和选择merge，这样会不会更高效？

**Comment by subaochen** [comment]
ok，没问题，直接PR即可
