### ISSUE TITLE
第八章问题

### ISSUE THREAD

**Issue by JamesLiAndroid** [subaochen/java-tutorial#9]
![8 2](https://cloud.githubusercontent.com/assets/6966410/23583964/53c2dac8-018e-11e7-8c92-cbc0b0b90d3a.png)

![interface enum](https://cloud.githubusercontent.com/assets/6966410/23583965/57efa64e-018e-11e7-93d8-d9b1e00901e8.png)

**Comment by subaochen** [comment]
implements接口，调用接口中定义的变量名是什么用法？能举个例子吗？

**Comment by JamesLiAndroid** [comment]
例子已经举过了，我写在了lyx文件中了，没有生成pdf，得去上班了！

**Comment by subaochen** [comment]
ok，just PR:-)
